from __future__ import annotations

from types import MappingProxyType
from typing import Final

# Generated by enumerating spglib.get_spacegroup_type(hall_number) for Hall
# numbers 1..530 and verifying that the 32 crystallographic Hermann-Mauguin
# point groups each map to exactly one Schoenflies symbol.
POINT_GROUP_SCHOENFLIES: Final = MappingProxyType(
    {
        "1": "C1",
        "-1": "Ci",
        "2": "C2",
        "m": "Cs",
        "2/m": "C2h",
        "222": "D2",
        "mm2": "C2v",
        "mmm": "D2h",
        "4": "C4",
        "-4": "S4",
        "4/m": "C4h",
        "422": "D4",
        "4mm": "C4v",
        "-42m": "D2d",
        "4/mmm": "D4h",
        "3": "C3",
        "-3": "C3i",
        "32": "D3",
        "3m": "C3v",
        "-3m": "D3d",
        "6": "C6",
        "-6": "C3h",
        "6/m": "C6h",
        "622": "D6",
        "6mm": "C6v",
        "-6m2": "D3h",
        "6/mmm": "D6h",
        "23": "T",
        "m-3": "Th",
        "432": "O",
        "-43m": "Td",
        "m-3m": "Oh",
    }
)


def point_group_schoenflies_symbol(point_group: str | None) -> str | None:
    if not point_group:
        return None
    return POINT_GROUP_SCHOENFLIES.get(point_group)
